### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by selmanca** [gattia/Slicer-T2mapping#3]
Hi Anthony,
I am trying to use T2 mapping module for knee cartilage. After choosing input volume and T2 output volume, I click apply and it gives this error message in Python Interactor:
module ‘string’ has no attribute ‘split’
I think that it may be related with incompatibility of the T2 mapping code with Python version (3.6.7) of the latest Slicer version.
Could you help me with this problem?
Thanks

**Comment by gattia** [comment]
Selmanca, 

Can you please send the whole error? So that I know what line it is and can make sure I fix this particular problem. 
When I get a chance I'll take a peak at updating to be python 3 compatible.

**Comment by selmanca** [comment]
I changed the "string" as "str" in the code(line 223):

`TE = numpy.array(map(float,str.split(t2Node.GetAttribute('MultiVolume.FrameLabels'),',')))`

Now it gives this:

```
C:/Users/selma/AppData/Local/NA-MIC/Slicer 4.13.0-2021-03-27/NA-MIC/Extensions-29804/T2mapping/lib/Slicer-4.13/qt-scripted-modules/T2mapping.py:227: RuntimeWarning: divide by zero encountered in log
  t2Log = numpy.log(t2Data)
C:/Users/selma/AppData/Local/NA-MIC/Slicer 4.13.0-2021-03-27/NA-MIC/Extensions-29804/T2mapping/lib/Slicer-4.13/qt-scripted-modules/T2mapping.py:227: RuntimeWarning: invalid value encountered in log
  t2Log = numpy.log(t2Data)
Traceback (most recent call last):
  File "C:/Users/selma/AppData/Local/NA-MIC/Slicer 4.13.0-2021-03-27/NA-MIC/Extensions-29804/T2mapping/lib/Slicer-4.13/qt-scripted-modules/T2mapping.py", line 159, in onApplyButton
    logic.run(self.inputSelector.currentNode(), self.T2outputSelector.currentNode(), self.PDoutputSelector.currentNode(), self.R2outputSelector.currentNode(), r2Cutoff, t2Cutoff)
  File "C:/Users/selma/AppData/Local/NA-MIC/Slicer 4.13.0-2021-03-27/NA-MIC/Extensions-29804/T2mapping/lib/Slicer-4.13/qt-scripted-modules/T2mapping.py", line 231, in run
    noEchoes = len(TE)
TypeError: len() of unsized object
```
TE supposed to be an array, but i am missing something i think

Thanks for the attention

**Comment by gattia** [comment]
Selmanca, thanks for pointing this out. Small bug that would make this unusable in the updated Slicer. 

You were on the right track - right functions and everything just off slightly in implementation. `str.split()` is not a function but instead every string has an inherent function `.split()`. For example. 

```
x = 'some,string,with,words,separated,by,commas'
x_as_list = x.split(',')
print(x_as_list)
```
that code will yield a list of the words, like this: 
```
['some', 'string', 'with', 'words', 'separated', 'by', 'commas']
```

The `','` passed to `.split()` in the above code can be anything that you want to use to split parts of the string. So, it could just be a space like `' '` if you wanted to split up words in a sentence. Using the same example as above: 

```
x = 'some string with words separated by spaces'
x_as_list = x.split(' ')
print(x_as_list)
```
that code will yield: 
```
['some', 'string', 'with', 'words', 'separated', 'by', 'spaces']
```

Hopefully that is of some use. Anyways, I've made the changes to the code and updated the master branch in this merge https://github.com/gattia/Slicer-T2mapping/pull/4. The master branch now works (I just tested locally). I forget how the updating on the Slicer end of things works, I think it updates every night? Or you might have to remove and then add the module again? Otherwise you can just clone the repository and put it in your local loadable modules folder - I assume you already figured this out based on the updates you mentioned. 

Let me know if this solves your problem. If it does we can hopefully close this issue.

**Comment by selmanca** [comment]
Thanks to you for your attention and explanation.
I am closing the issue.
